version: "3.7"

services:
  reverse-proxy:
    build: ./proxy
    ports:
      - 8080:8080
    restart: always
    environment:
      PORT: 8080
    volumes:
      - ./proxy/src:/usr/src/app/src
  wallet:
    build: ../../../2-wallet-ui
    ports:
      - "3000:3000"
  belgium-gov:
    build:
      context: ../../packages/belgium-gov
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${BELGIUM_GOV_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${BELGIUM_GOV_PUBLIC_URL:?BELGIUM_GOV_PUBLIC_URL is not defined or empty}
    ports:
      - "${BELGIUM_GOV_PORT}:${BELGIUM_GOV_PORT}"
    volumes:
      - ../../packages/belgium-gov/public:/usr/src/app/public
      - ../../packages/belgium-gov/src:/usr/src/app/src
  demonstrator:
    build:
      context: ../../packages/demonstrator
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${DEMONSTRATOR_PORT}
      REACT_APP_BELGIUM_GOV_URL: ${BELGIUM_GOV_PUBLIC_URL:?BELGIUM_GOV_PUBLIC_URL is not defined or empty}
      REACT_APP_EU_FUNDING_URL: ${EU_FUNDING_PUBLIC_URL:?EU_FUNDING_PUBLIC_URL is not defined or empty}
      REACT_APP_FLEMISH_GOV_URL: ${FLEMISH_GOV_PUBLIC_URL:?FLEMISH_GOV_PUBLIC_URL is not defined or empty}
      REACT_APP_SPANISH_UNIVERSITY_URL: ${SPANISH_UNIVERSITY_PUBLIC_URL:?SPANISH_UNIVERSITY_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
    ports:
      - "${DEMONSTRATOR_PORT}:${DEMONSTRATOR_PORT}"
    volumes:
      - ../../packages/demonstrator/public:/usr/src/app/public
      - ../../packages/demonstrator/src:/usr/src/app/src
  eu-funding:
    build:
      context: ../../packages/eu-funding
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${EU_FUNDING_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${EU_FUNDING_PUBLIC_URL:?EU_FUNDING_PUBLIC_URL is not defined or empty}
    ports:
      - "${EU_FUNDING_PORT}:${EU_FUNDING_PORT}"
    volumes:
      - ../../packages/eu-funding/public:/usr/src/app/public
      - ../../packages/eu-funding/src:/usr/src/app/src
  flemish-gov:
    build:
      context: ../../packages/flemish-gov
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${FLEMISH_GOV_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${FLEMISH_GOV_PUBLIC_URL:?FLEMISH_GOV_PUBLIC_URL is not defined or empty}
    ports:
      - "${FLEMISH_GOV_PORT}:${FLEMISH_GOV_PORT}"
    volumes:
      - ../../packages/flemish-gov/public:/usr/src/app/public
      - ../../packages/flemish-gov/src:/usr/src/app/src
  spanish-university:
    build:
      context: ../../packages/spanish-university
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${SPANISH_UNIVERSITY_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${SPANISH_UNIVERSITY_PUBLIC_URL:?SPANISH_UNIVERSITY_PUBLIC_URL is not defined or empty}
    ports:
      - "${SPANISH_UNIVERSITY_PORT}:${SPANISH_UNIVERSITY_PORT}"
    volumes:
      - ../../packages/spanish-university/public:/usr/src/app/public
      - ../../packages/spanish-university/src:/usr/src/app/src
