version: "3.7"

services:
  reverse-proxy:
    build: ./proxy
    ports:
      - 8080:8080
    environment:
      HTTPS: "false"
      PORT: 8080
      BELGIUM_GOV_PORT: ${BELGIUM_GOV_PORT:?BELGIUM_GOV_PORT is not defined or empty}
      DEMONSTRATOR_PORT: ${DEMONSTRATOR_PORT:?DEMONSTRATOR_PORT is not defined or empty}
      EU_FUNDING_PORT: ${EU_FUNDING_PORT:?EU_FUNDING_PORT is not defined or empty}
      FLEMISH_GOV_PORT: ${FLEMISH_GOV_PORT:?FLEMISH_GOV_PORT is not defined or empty}
      SPANISH_UNIVERSITY_PORT: ${SPANISH_UNIVERSITY_PORT:?SPANISH_UNIVERSITY_PORT is not defined or empty}
      NOTARY_PORT: ${NOTARY_PORT:?NOTARY_PORT is not defined or empty}
    volumes:
      - ./proxy/src:/usr/src/app/src
  wallet:
    build:
      context: ../../../2-wallet-ui
      args:
        REACT_APP_BELGIUM_GOV_URL: ${BELGIUM_GOV_PUBLIC_URL:?BELGIUM_GOV_PUBLIC_URL is not defined or empty}
        REACT_APP_DIPLOMA: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
        REACT_APP_EUROPEAN_FUNDING_URL: ${EU_FUNDING_PUBLIC_URL:?EU_FUNDING_PUBLIC_URL is not defined or empty}
        REACT_APP_FLEMISH_GOV_URL: ${FLEMISH_GOV_PUBLIC_URL:?FLEMISH_GOV_PUBLIC_URL is not defined or empty}
        REACT_APP_SPANISH_UNIVERSITY_URL: ${SPANISH_UNIVERSITY_PUBLIC_URL:?SPANISH_UNIVERSITY_PUBLIC_URL is not defined or empty}
        REACT_APP_WALLET: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
        REACT_APP_NOTARIZATION: ${REACT_APP_NOTARY_URL:?REACT_APP_NOTARY_URL is not defined or empty}
        REACT_APP_WALLET_API: ${REACT_APP_WALLET_API:?REACT_APP_WALLET_API is not defined or empty}
        REACT_APP_ID_HUB_API: ${REACT_APP_ID_HUB_API:?REACT_APP_ID_HUB_API is not defined or empty}
        REACT_APP_EULOGIN: ${REACT_APP_EULOGIN:?REACT_APP_EULOGIN is not defined or empty}
  demonstrator:
    build:
      context: ../../packages/demonstrator
      dockerfile: Dockerfile.dev
    environment:
      HTTPS: "false"
      PORT: ${DEMONSTRATOR_PORT}
      REACT_APP_BELGIUM_GOV_URL: ${BELGIUM_GOV_PUBLIC_URL:?BELGIUM_GOV_PUBLIC_URL is not defined or empty}
      REACT_APP_EU_FUNDING_URL: ${EU_FUNDING_PUBLIC_URL:?EU_FUNDING_PUBLIC_URL is not defined or empty}
      REACT_APP_FLEMISH_GOV_URL: ${FLEMISH_GOV_PUBLIC_URL:?FLEMISH_GOV_PUBLIC_URL is not defined or empty}
      REACT_APP_SPANISH_UNIVERSITY_URL: ${SPANISH_UNIVERSITY_PUBLIC_URL:?SPANISH_UNIVERSITY_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_NOTARY_URL: ${REACT_APP_NOTARY_URL:?REACT_APP_NOTARY_URL is not defined or empty}
    ports:
      - "${DEMONSTRATOR_PORT}:${DEMONSTRATOR_PORT}"
    volumes:
      - ../../packages/demonstrator/public:/usr/src/app/public
      - ../../packages/demonstrator/src:/usr/src/app/src

  # Diploma UC frontends

  belgium-gov:
    build:
      context: ../../packages/belgium-gov
      dockerfile: Dockerfile.dev
    environment:
      HTTPS: "false"
      PORT: ${BELGIUM_GOV_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_VERIFIABLE_ID_URL: ${REACT_APP_VERIFIABLE_ID_URL:?REACT_APP_VERIFIABLE_ID_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${BELGIUM_GOV_PUBLIC_URL:?BELGIUM_GOV_PUBLIC_URL is not defined or empty}
    ports:
      - "${BELGIUM_GOV_PORT}:${BELGIUM_GOV_PORT}"
    volumes:
      - ../../packages/belgium-gov/public:/usr/src/app/public
      - ../../packages/belgium-gov/src:/usr/src/app/src
  eu-funding:
    build:
      context: ../../packages/eu-funding
      dockerfile: Dockerfile.dev
    environment:
      HTTPS: "false"
      PORT: ${EU_FUNDING_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${EU_FUNDING_PUBLIC_URL:?EU_FUNDING_PUBLIC_URL is not defined or empty}
    ports:
      - "${EU_FUNDING_PORT}:${EU_FUNDING_PORT}"
    volumes:
      - ../../packages/eu-funding/public:/usr/src/app/public
      - ../../packages/eu-funding/src:/usr/src/app/src
  flemish-gov:
    build:
      context: ../../packages/flemish-gov
      dockerfile: Dockerfile.dev
    environment:
      HTTPS: "false"
      PORT: ${FLEMISH_GOV_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_DIPLOMA_API_URL: ${REACT_APP_DIPLOMA_API_URL:?REACT_APP_DIPLOMA_API_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${FLEMISH_GOV_PUBLIC_URL:?FLEMISH_GOV_PUBLIC_URL is not defined or empty}
    ports:
      - "${FLEMISH_GOV_PORT}:${FLEMISH_GOV_PORT}"
    volumes:
      - ../../packages/flemish-gov/public:/usr/src/app/public
      - ../../packages/flemish-gov/src:/usr/src/app/src
  spanish-university:
    build:
      context: ../../packages/spanish-university
      dockerfile: Dockerfile.dev
    environment:
      HTTPS: "false"
      PORT: ${SPANISH_UNIVERSITY_PORT}
      REACT_APP_DEMONSTRATOR_URL: ${DEMONSTRATOR_PUBLIC_URL:?DEMONSTRATOR_PUBLIC_URL is not defined or empty}
      REACT_APP_WALLET_URL: ${REACT_APP_WALLET_URL:?REACT_APP_WALLET_URL is not defined or empty}
      REACT_APP_URL: ${SPANISH_UNIVERSITY_PUBLIC_URL:?SPANISH_UNIVERSITY_PUBLIC_URL is not defined or empty}
    ports:
      - "${SPANISH_UNIVERSITY_PORT}:${SPANISH_UNIVERSITY_PORT}"
    volumes:
      - ../../packages/spanish-university/public:/usr/src/app/public
      - ../../packages/spanish-university/src:/usr/src/app/src

  # Notary

  notarization:
    build: ../../../1-notarization-uc
    logging:
      options:
        max-size: "100m"
        max-file: "50"
    ports:
      - "${NOTARY_PORT}:${NOTARY_PORT}"
    environment:
      HTTPS: "OFF"
      PORT: ${NOTARY_PORT}
      PUBLIC_URL: ${REACT_APP_NOTARY_URL}
      NODE_ENV: development
    depends_on:
      - mongodb
    # Wait 15 seconds before starting notary
    command: /bin/sh -c "sleep 15 && npm start"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
